# Generated by Django 3.2.5 on 2022-01-25 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("member", "0004_auto_20220125_1407"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordleAnswers",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("answer", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "wordle_answer",
            },
        ),
        migrations.CreateModel(
            name="WordleRanks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_rank", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.wordleuser",
                    ),
                ),
            ],
            options={
                "db_table": "wordle_rank",
            },
        ),
        migrations.CreateModel(
            name="WordleDayRanks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                ("create_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="member.wordleuser",
                    ),
                ),
            ],
            options={
                "db_table": "wordle_dayRank",
            },
        ),
    ]
