# Generated by Django 3.2.11 on 2022-01-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordledayranks',
            old_name='create_at',
            new_name='recorded_at',
        ),
        migrations.AddField(
            model_name='wordledayranks',
            name='user_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='wordledayranks',
            table='wordle_dayrank',
        ),
    ]
