# Generated by Django 3.2.5 on 2022-01-24 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("user_pw", models.CharField(db_column="password", max_length=50)),
                ("user_name", models.CharField(db_column="name", max_length=50)),
                (
                    "user_class",
                    models.IntegerField(
                        db_column="class",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
            ],
        ),
    ]
