# Generated by Django 3.2.5 on 2022-01-24 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_alter_member_user_class"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Member",
            new_name="User",
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
