# Generated by Django 3.2.5 on 2022-01-25 05:07

from django.db import migrations, models
import member.validators


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_auto_20220124_1927"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                (
                    "user_pw",
                    models.CharField(
                        db_column="password",
                        max_length=50,
                        validators=[member.validators.password_validator],
                    ),
                ),
                ("user_name", models.CharField(db_column="name", max_length=50)),
                (
                    "user_class",
                    models.CharField(
                        choices=[
                            ("수도권1", "수도권1반"),
                            ("수도권2", "수도권2반"),
                            ("수도권3", "수도권3반"),
                            ("수도권4", "수도권4반"),
                            ("수도권5", "수도권5반"),
                            ("강원권1", "강원권1반"),
                            ("충남충북", "충남/충북권1반"),
                            ("대구경북", "대구/경북권1반"),
                            ("전남전북", "전남/전북권1반"),
                            ("부산경남", "부산/경남권1반"),
                        ],
                        db_column="class",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "wordle_user",
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
