# Generated by Django 3.2.11 on 2022-01-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0005_auto_20220125_1443"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordleuser",
            name="user_profile",
            field=models.FileField(
                db_column="profile", null=True, upload_to="%Y/%m/%d"
            ),
        ),
    ]
