# Generated by Django 3.2.11 on 2022-01-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Calendar",
        ),
    ]
